### PR TITLE
bumped ngx_lua required version to 0.9.17

### PR DESCRIPTION
**Pull request by spacewander**
For #14

### CODE REVIEW

**Comment by agentzh** [comment]
@spacewander Seems like `*_by_lua_block` was first introduced in ngx_lua 0.9.19? See

http://openresty.org/en/changelog-1009003.html

**Comment by spacewander** [comment]
Well, according to https://github.com/openresty/lua-nginx-module#init_by_lua_block , `*_by_lua_block` was introduced in ngx_lua 0.9.17.
And it was introduced via that commit: https://github.com/openresty/lua-nginx-module/commit/6b558cd4bd18403c6a071ca87ffd35dbd0ad612e

**Comment by agentzh** [comment]
@spacewander The initial `*_by_lua_block*` implementation was buggy. We'd better require a later version of ngx_lua. And versions earlier than 0.9.17 cannot run your check in the Lua code anyway (an nginx configuration loading error will be thrown out very early).

**Comment by agentzh** [comment]
@spacewander I've bumped the minimum version of ngx_lua required to 0.10.5 since earlier versions contain known bugs in `*_by_lua_block` handling.

**Pull request closed without merging**
