### PR TITLE
optimize: remove unwanted exit status handling

### PR DESCRIPTION
**Pull request by thibaultcha**

### CODE REVIEW

**Comment by agentzh** [comment]
@thibaultcha Mind to add some tests for this change? ;) Thanks!

**Comment by thibaultcha** [comment]
Added! This will conflict with that other PR about stacktraces, so I'll take care of resolving them in time :)

**Comment by agentzh** [comment]
@thibaultcha Mind to resolve conflicts in this one? Thanks!

**Comment by thibaultcha** [comment]
@agentzh Done!

**Comment by thibaultcha** [comment]
(ping)

**Comment by agentzh** [comment]
@thibaultcha Merged. Thanks!

**Pull request closed without merging**
